### ISSUE TITLE
Content negotiation for format selection

### ISSUE THREAD

**Issue by demaniak** [WhereIsMyTransport/docs#10]
Not really an issue, more a suggestion: use `Content-Type` header to select response type, instead of the `format` key in the JSON post.

Even though (afaik) there is no standard MIME type for protocolbuf at this point (and it is debatable if there should/CAN be), something like `X-wimt-alert/protobuf` should slot nicely into normal HTTP usage. 
It will also make it possible to easily implement different formats for the channel creation messages.

**Comment by chrisk1ng** [comment]
Thanks for the feedback, we will take it into consideration!
