### ISSUE TITLE
DateTime Discrepancy

### ISSUE THREAD

**Issue by seanbrodie** [WhereIsMyTransport/docs#9]
The `earliestArrivalTime` parameter doesn't accept yyyy-MM-ddThh:mmZ (where the seconds are omitted) which abides by the ISO 8601 format and is in fact given as an example in your DateTime spec.

The response given is helpful but perhaps the docs should be modified.

**Comment by davenewza** [comment]
Thanks for reporting this to us! We are looking into it and will get back to you. For now, you can provide the full string; for example, 2016-11-19T07:22:00Z.

**Comment by davenewza** [comment]
@seanbrodie We will have the fix released tomorrow morning. I'll let you know once all is in production.

**Comment by ivansams** [comment]
@seanbrodie @davenewza This fix is now in production. The API now fully supports the ISO 8601 format in all its permutations, including ordinal dates and week-based dates. You can also omit from the small-unit side (seconds), but note that you cannot omit from the big-unit side (years). Thanks for pointing this out!
